Support for New Versions of Django
fabiocaccamo/django-freeze pull request #12
Opened 2022-09-03 08:37 UTC by pvanfas

2022-09-06 09:20 UTC, fabiocaccamo requested changes

2022-09-06 09:20 UTC, fabiocaccamo commented on freeze/__init__.py
> -
Why?

2022-09-06 09:20 UTC, fabiocaccamo commented on freeze/version.py
> +__version__ = "0.7"
Don't worry about the library version.

2022-09-06 09:20 UTC, fabiocaccamo commented on freeze/urls.py
> +from django.urls import path
Please add conditional import depending on django version for bacward-compatibility.

2022-09-06 15:56 UTC, closed without merging

2022-09-07 02:10 UTC, fabiocaccamo commented
Why you closed this?

2022-09-22 12:32 UTC, pvanfas commented
i will reopen with backward compatibility changes